import { mountBooking } from './booking-flow.js';

const services=[{name:'Extensão de Cílios',price:130,durationMinutes:120,image:'/bella-lash/extension.png'},{name:'Manutenção de Cílios',price:90,durationMinutes:60,image:'/bella-lash/maintenance.png'},{name:'Remoção de Cílios',price:50,durationMinutes:30,image:'/bella-lash/removal.png'}];
const calendar='<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><rect x="4" y="5" width="16" height="16" rx="2"/><path d="M8 2v6m8-6v6M4 11h16"/></svg>';let selected=0;let bookings=[];try{bookings=JSON.parse(localStorage.getItem('bella-lash-bookings')||'[]');if(!Array.isArray(bookings))bookings=[]}catch{};
const money=n=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const home=document.getElementById('home');services.forEach((s,i)=>{const article=document.createElement('article');article.className='service';article.innerHTML='<img alt="'+s.name+'" src="'+s.image+'"><div class="detail"><h2>'+s.name+'</h2><div class="row"><div class="service-meta"><span class="price">'+money(s.price)+'</span><span class="duration" aria-label="Duração do serviço"><svg class="duration-clock" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg>'+s.durationMinutes+' min</span></div><button class="book">'+calendar+'Agendar</button></div></div>';article.querySelector('button').onclick=()=>{selected=i;const root=document.createElement('div');document.body.append(root);mountBooking(root,s,()=>root.remove())};home.append(article)});
function show(view){['home','appointments'].forEach(id=>document.getElementById(id).classList.toggle('hidden',id!==view));document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='appointments')render()}
function render(){const list=document.getElementById('list');list.replaceChildren();if(!bookings.length){const e=document.createElement('div');e.className='empty';e.textContent='Você ainda não possui agendamentos salvos.';list.append(e)}bookings.forEach((b,i)=>{const card=document.createElement('div');card.className='saved';const title=document.createElement('strong');title.textContent=b.service;const detail=document.createElement('p');detail.textContent=b.name+' · '+b.date.split('-').reverse().join('/')+' às '+b.time;const cancel=document.createElement('button');cancel.textContent='Cancelar horário';cancel.onclick=()=>{bookings.splice(i,1);persist();render()};card.append(title,detail,cancel);list.append(card)})}
function persist(){try{localStorage.setItem('bella-lash-bookings',JSON.stringify(bookings))}catch{alert('Não foi possível salvar neste navegador.')}}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));document.getElementById('back').onclick=()=>show('home');document.getElementById('more').onclick=()=>document.getElementById('info').showModal();document.getElementById('closeInfo').onclick=()=>document.getElementById('info').close();document.getElementById('close').onclick=()=>document.getElementById('booking').close();const date=document.querySelector('[name=date]');const now=new Date();date.min=[now.getFullYear(),String(now.getMonth()+1).padStart(2,'0'),String(now.getDate()).padStart(2,'0')].join('-');document.getElementById('form').onsubmit=e=>{e.preventDefault();const data=new FormData(e.target);const dt=new Date(data.get('date')+'T'+data.get('time'));if(dt<=new Date()){alert('Escolha um horário futuro.');return}bookings.push({service:services[selected].name,name:data.get('name').trim(),date:data.get('date'),time:data.get('time')});persist();document.getElementById('booking').close();e.target.reset();show('appointments')};
